#!/usr/bin/env python3
"""Build the photo gallery served by index.html from the originals in pics/.

    pics/           drop folder for originals (HEIC/JPEG/PNG straight from the phone);
                    never deployed, never committed
    gallery/        what the site serves (deployed by deploy.sh, gitignored):
                      <stem>.jpg        web copy, long edge <= 1800 px, EXIF/GPS stripped
                      <stem>-thumb.jpg  strip tile, 400 px tall
                      gallery.js        manifest read by the photo band in index.html
    pics/captions.txt   optional, one "IMG_7412: caption text" per line (stem or filename)

Run it again after adding photos to pics/: only new or changed originals are
converted, and gallery files whose original is gone are removed.  Needs
ImageMagick (`brew install imagemagick`, HEIC support included).

    ./make-gallery.py            # incremental
    ./make-gallery.py --force    # reconvert everything
"""
import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "pics"
OUT = ROOT / "gallery"
MANIFEST = OUT / "gallery.js"
CAPTIONS = SRC / "captions.txt"
EXTS = {".heic", ".heif", ".jpg", ".jpeg", ".png"}
FULL_MAX = 1800   # long edge of the web copy
THUMB_H = 400     # height of the strip tile


def magick(*args):
    return subprocess.run(["magick", *args], check=True, capture_output=True, text=True).stdout


def identify(path):
    """(width, height, taken) of the original, honouring the EXIF orientation."""
    out = magick("identify", "-quiet", "-format",
                 "%w|%h|%[EXIF:Orientation]|%[EXIF:DateTimeOriginal]", str(path))
    w, h, orient, taken = out.split("|")
    w, h = int(w), int(h)
    if orient in ("5", "6", "7", "8"):
        w, h = h, w
    if re.match(r"\d{4}:\d\d:\d\d \d\d:\d\d:\d\d", taken or ""):
        taken = datetime.strptime(taken, "%Y:%m:%d %H:%M:%S")
    else:
        taken = datetime.fromtimestamp(path.stat().st_mtime)
    return w, h, taken


def convert(src, dst, geometry, quality):
    magick(str(src), "-auto-orient", "-strip", "-resize", geometry,
           "-quality", str(quality), "-sampling-factor", "4:2:0", "-interlace", "JPEG", str(dst))


def read_captions():
    caps = {}
    if CAPTIONS.exists():
        for line in CAPTIONS.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or ":" not in line:
                continue
            key, text = line.split(":", 1)
            caps[Path(key.strip()).stem] = text.strip()
    return caps


def main():
    force = "--force" in sys.argv
    if not SRC.is_dir():
        sys.exit(f"no {SRC.relative_to(ROOT)}/ folder")
    OUT.mkdir(exist_ok=True)
    captions = read_captions()

    originals = sorted(p for p in SRC.iterdir() if p.suffix.lower() in EXTS and not p.name.startswith("."))
    stems = {p.stem for p in originals}
    items, converted = [], 0

    for src in originals:
        full = OUT / f"{src.stem}.jpg"
        thumb = OUT / f"{src.stem}-thumb.jpg"
        stale = force or not full.exists() or not thumb.exists() \
            or full.stat().st_mtime < src.stat().st_mtime
        if stale:
            convert(src, full, f"{FULL_MAX}x{FULL_MAX}>", 82)
            convert(src, thumb, f"x{THUMB_H}", 78)
            converted += 1
            print(f"  {src.name} -> {full.name} ({full.stat().st_size // 1024} KB), "
                  f"{thumb.name} ({thumb.stat().st_size // 1024} KB)")
        w, h, taken = identify(src)
        item = {"f": src.stem, "w": w, "h": h, "t": taken.strftime("%Y-%m-%dT%H:%M:%S")}
        if src.stem in captions:
            item["c"] = captions[src.stem]
        items.append(item)

    # gallery files whose original was removed from pics/
    removed = 0
    for f in OUT.glob("*.jpg"):
        stem = f.stem[:-6] if f.stem.endswith("-thumb") else f.stem
        if stem not in stems:
            f.unlink()
            removed += 1

    items.sort(key=lambda i: (i["t"], i["f"]))
    payload = {"generated": datetime.now().strftime("%Y-%m-%dT%H:%M:%S"), "items": items}
    MANIFEST.write_text("// generated by make-gallery.py, do not edit\n"
                        "window.STINT_GALLERY = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
                        encoding="utf-8")
    total = sum(f.stat().st_size for f in OUT.glob("*.jpg"))
    thumbs = sum(f.stat().st_size for f in OUT.glob("*-thumb.jpg"))
    print(f"{len(items)} photos in {MANIFEST.relative_to(ROOT)} "
          f"({converted} converted, {removed} removed); gallery/ is {total / 1e6:.1f} MB, "
          f"thumbnails {thumbs / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
